### ISSUE TITLE
Looker SDK auth.login_user() doesn't work as expected

### ISSUE THREAD

**Issue by dbuzolin-zencore** [looker-open-source/sdk-codegen#1369]
Trying simple example with sudo (the user_id=5 does exists in the system)
looker-sdk==23.16.0
```
sdk.me()  # user for originally configured credentials
sdk.auth.login_user(5)
sdk.me()  # user with id 5
sdk.auth.logout()
sdk.me()  # user for originally configured credentials
```
Produces this output:

```
Traceback (most recent call last):
  File "/Users/db/repos/looker-utils/src/python/list_dashboards.py", line 274, in <module>
    main(args)
  File "/Users/db/repos/looker-utils/src/python/list_dashboards.py", line 219, in main
    sdk.auth.login_user(5)
  File "/Users/db/.pyenv/versions/3.9.13/lib/python3.9/site-packages/looker_sdk/rtl/auth_session.py", line 118, in login_user
    self._login_sudo(transport_options or {})
  File "/Users/db/.pyenv/versions/3.9.13/lib/python3.9/site-packages/looker_sdk/rtl/auth_session.py", line 172, in _login_sudo
    response = self._ok(
  File "/Users/db/.pyenv/versions/3.9.13/lib/python3.9/site-packages/looker_sdk/rtl/auth_session.py", line 240, in _ok
    raise error.SDKError(response.value.decode(encoding="utf-8"))
```

Sudo to this user works fine in UI

**Comment by dbuzolin-zencore** [comment]
Please close this, this was due to wrong Looker instance used in initing the SDK.
