### ISSUE TITLE
Buffering Error on create_git_deploy_key

### ISSUE THREAD

**Issue by jsrice7391** [looker-open-source/sdk-codegen#195]
I am using the SDK to automate the creation of looker projects. One of the things that I am doing is creating an ssh key for the new project by calling the create_git_deploy_key command from the sdk.

Here is My implementation:
```js
const deploy_key = await sdk.ok(
   sdk.create_git_deploy_key({
       project_id: "it-services-looker-five"
    })).catch(err => {
        console.log(err)
        console.log("Something went wrong when getting the deploy key")
    })
```

I expect to get back the SSH key as a string (bold move). But I am getting the following error.
```bash
message:"404 - {"type":"Buffer","data":[123,34,109,101,115,115,97,103,101,34,58,34,78,111,116,32,102,111,117,110,100,34,44,34,100,111,99,117,109,101,110,116,97,116,105,111,110,95,117,114,108,34,58,34,104,116,116,112,58,47,47,100,111,99,115,46,108,111,111,107,101,114,46,99,111,109,47,34,125]}"
stack:"Error: 404 - {"type":"Buffer","data":[123,34,109,101,115,115,97,103,101,34,58,34,78,111,116,32,102,111,117,110,100,34,44,34,100,111,99,117,109,101,110,116,97,116,105,111,110,95,117,114,108,34,58,34,104,116,116,112,58,47,47,100,111,99,115,46,108,111,111,107,101,114,46,99,111,109,47,34,125]}
    at sdkError (/Users/justinrice/Documents/IndigoGit/dwight-api/node_modules/@looker/sdk/dist/rtl/transport.js:271:16)
    at Object.<anonymous> (/Users/justinrice/Documents/IndigoGit/dwight-api/node_modules/@looker/sdk/dist/rtl/transport.js:312:31)
    at step (/Users/justinrice/Documents/IndigoGit/dwight-api/node_modules/@looker/sdk/dist/rtl/transport.js:56:23)
    at Object.next (/Users/justinrice/Documents/IndigoGit/dwight-api/node_modules/@looker/sdk/dist/rtl/transport.js:37:53)
    at fulfilled (/Users/justinrice/Documents/IndigoGit/dwight-api/node_modules/@looker/sdk/dist/rtl/transport.js:28:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by jkaster** [comment]
Hi @jsrice7391 this looks like Typescript code. Is this the node run-time? We return `404` for unauthorized access as well as a bad URL.

Also, I've improved the error handling for these `"Buffer"` obfuscations in newer Typescript SDK releases so you should be able to get the actual data rendered as a UTF-8 string now rather than the decoded representation of `"data"` as an integer array.

Let me know if this is still an issue for you. Thanks!

**Comment by jsrice7391** [comment]
@jkaster It is not TypeScript. Just plain old JS.
