### ISSUE TITLE
Python: lookml_model_explore() raises an error - RuntimeError: super(): __class__ cell not found

### ISSUE THREAD

**Issue by erik-heintare** [looker-open-source/sdk-codegen#334]
All other functions work as expected but when I use lookml_model_explore() with whatever explore_name then I get an error `RuntimeError: super(): __class__ cell not found`. I can bypass the error when defining fields parameter without fields value, like fields="id, name, description" then it works as expected. Since fields is the main value I'm looking for then would be nice to know what is causing this issue.

Full code:
```
import looker_sdk

sdk = looker_sdk.init40()

a = sdk.lookml_model_explore(lookml_model_name='example',explore_name='example2')

print(a)
```

Full error report: 

```
Traceback (most recent call last):
  File "/Users/erik/Documents/looker/quality/main.py", line 5, in <module>
    a = sdk.lookml_model_explore(lookml_model_name='example',explore_name='example2')
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/sdk/api40/methods.py", line 5226, in lookml_model_explore
    response = self.get(
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/api_methods.py", line 152, in get
    return self._return(response, structure)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/api_methods.py", line 101, in _return
    ret = self.deserialize(data=value, structure=structure)  # type: ignore
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/serialize.py", line 72, in deserialize
    response: TDeserializeReturn = converter.structure(  # type: ignore
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 387, in _structure_union
    return self._structure_func.dispatch(other)(obj, other)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/serialize.py", line 125, in forward_ref_structure_hook
    instance = converter.structure_attrs_fromdict(data, actual_type)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 387, in _structure_union
    return self._structure_func.dispatch(other)(obj, other)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 325, in _structure_list
    return [
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 326, in <listcomp>
    self._structure_func.dispatch(elem_type)(e, elem_type)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/serialize.py", line 125, in forward_ref_structure_hook
    instance = converter.structure_attrs_fromdict(data, actual_type)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 387, in _structure_union
    return self._structure_func.dispatch(other)(obj, other)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/serialize.py", line 122, in forward_ref_structure_hook
    instance = converter.structure(data, actual_type)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/cattr/converters.py", line 264, in _structure_call
    return cl(obj)
  File "/Users/erik/.pyenv/versions/3.8.2/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/Users/erik/.local/share/virtualenvs/quality-09nN-6uz/lib/python3.8/site-packages/looker_sdk/rtl/model.py", line 173, in safe_enum__new__
    return super().__new__(cls, value)
RuntimeError: super(): __class__ cell not found
```

**Comment by erik-heintare** [comment]
Additional comment here is that I used [this](https://github.com/looker-open-source/sdk-codegen/blob/master/python/README.rst) to create virtualenv and the same error occurs with all model&explore pairs, so it's not related with weird fields or etc.

**Comment by joeldodge79** [comment]
It looks like there's a bug in our codegen around how we interpret the `LookmlModelExploreField.user_attribute_filter_types` type. It should be an `Optional[Sequence["UserAttributeFilterTypes"]]`, not a `Optional["UserAttributeFilterTypes"]`

We recently introduced [Enum types](https://github.com/looker-open-source/sdk-codegen/blob/master/python/CHANGELOG.md#013b16) and this looks like a bug in that code. I'll get a fix up shortly

**Comment by joeldodge79** [comment]
https://pypi.org/project/looker-sdk/0.1.3b17/ has the fix
